# -*- coding: utf-8 -*-
"""mean_var_std.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1th43Z6kA8ENCIEaacY3j4gOh2bKRPqWY
"""

import numpy as np

def calculate(list):
  a = 9
  if len(list) != 9:
    raise ValueError("List must contain exactly 9 numbers.")
  holder = np.array(list)
  x = holder.reshape(3,3)

  mean = [np.mean(x, axis=0).tolist(), np.mean(x, axis=1).tolist(), np.mean(x)]
  variance = [np.var(x, axis=0).tolist(), np.var(x, axis=1).tolist(), np.var(x)]
  std = [np.std(x, axis=0).tolist(), np.std(x, axis=1).tolist(), np.std(x)]
  max = [np.max(x, axis=0).tolist(), np.max(x, axis=1).tolist(), np.max(x)]
  min = [np.min(x, axis=0).tolist(), np.min(x, axis=1).tolist(), np.min(x)]
  sum = [np.sum(x, axis=0).tolist(), np.sum(x, axis=1).tolist(), np.sum(x)]
  return {'mean': mean,
    'variance': variance,
    'standard deviation': std,
    'max': max,
    'min': min,
    'sum': sum
  }