# -*- coding: utf-8 -*-
"""medical_data_visualizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xZr4eDgJ6w4ipVUalHHGNdRayaHSGASn
"""



import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# 1
df = ('medical_examination.csv',
                 index_col='id')

# 2
df['overweight'] = (df['weight'] / ((df['height'] / 100) ** 2) > 25).astype(int)

# 3
df['cholesterol'] = (df['cholesterol'] > 1).astype(int)
df['gluc'] = (df['gluc'] > 1).astype(int)

# 4
def draw_cat_plot():
    # 5
    df_cat = (df
          .melt(id_vars=['cardio'], value_vars=['active', 'alco', 'cholesterol', 'gluc', 'overweight', 'smoke'])
          )

    # 6
    df_cat = (df_cat
          .groupby(['cardio', 'variable', 'value'])
          .agg({'value': 'count'})
          .rename(columns={'value': 'total'}))

    # 7



    # 8
    fig = sns.catplot(data=df_cat, x="variable", y="total", hue="value", col="cardio", kind="bar")


    # 9
    fig.savefig('catplot.png')
    return fig


# 10
def draw_heat_map():
    # 11
    df_heat = (df
           .loc[(df['ap_hi'] >= (df['ap_lo']))]
           .loc[df['height'] >= df['height'].quantile(0.025)]
           .loc[df['height'] <= df['height'].quantile(0.975)]
           .loc[df['weight'] >= df['weight'].quantile(0.025)]
           .loc[df['weight'] <= df['weight'].quantile(0.975)]
           .reset_index()
           )

    # 12
    corr = df_heat.corr()

    # 13
    mask = np.triu(np.ones_like(corr, dtype=bool))



    # 14
    fig, ax = plt.subplots(figsize=(6, 6))


    # 15
    im = sns.heatmap(corr, mask=mask, fmt='.1f', annot=True)
    ax.set_title('Correlation Heatmap')


    # 16
    fig.savefig('heatmap.png')
    return fig