# -*- coding: utf-8 -*-
"""sea_level_predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k1CbCL4SCjO4uVMGgBk5ZohoNzMCrC3B
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import linregress

def draw_plot():
    # Read data from file
    df = pd.read_csv('epa-sea-level.csv')
    x = df['Year']
    y = df['CSIRO Adjusted Sea Level']
    # Create scatter plot
    fig, ax = plt.subplots()
    scatter = plt.scatter(x, y)


    # Create first line of best fit
    slope, intercept, r, p, std = linregress(x, y)
    x_new = np.arange(1880, 2050, 1)
    y_new = slope*x_new + intercept
    plt.plot(x_new, y_new, 'r')

    # Create second line of best fit
    df_new = df.loc[df['Year'] >= 2000]
    x_2 = df_new['Year']
    y_2 = df_new['CSIRO Adjusted Sea Level']
    slope, intercept, r, p, std = linregress(x_2, y_2)
    x_new_2 = np.arange(2000, 2050, 1)
    y_new_2 = slope*x_new_2 + intercept
    plt.plot(x_new_2, y_new_2, 'g')

    # Add labels and title
    plt.title('Rise in Sea Level')
    plt.xlabel('Year')
    plt.ylabel('Sea Level (inches)')

    # Save plot and return data for testing (DO NOT MODIFY)
    plt.savefig('sea_level_plot.png')
    return plt.gca()